def _best_split(self, args, X, y):
    """Find the best split for a node.
    "Best" means that the average impurity of the two children, weighted by their
    population, is the smallest possible. Additionally it must be less than the
    impurity of the current node.
    To find the best split, we loop through all the features, and consider all the
    midpoints between adjacent training samples as possible thresholds. We compute
    the Gini impurity of the split generated by that particular feature/threshold
    pair, and return the pair with smallest impurity.
    Returns:
        best_idx: Index of the feature for best split, or None if no split is found.
        best_thr: Threshold to use for the split, or None if no split is found.
    """
    # Need at least two elements to split a node.
    if y.size < args.min_to_split:  # +++
        return None, None

    # Count of each class in the current node.
    num_parent = [np.sum(y == c) for c in range(self.n_classes_)]

    # Gini of current node.
    best_gini = 1.0 - sum((n / y.size) ** 2 for n in num_parent)
    best_idx, best_thr = None, None

    # Loop through all features.
    for idx in range(self.n_features_):
        # Sort data along selected feature.
        thresholds, classes = zip(*sorted(zip(X[:, idx], y)))

        # We could actually split the node according to each feature/threshold pair
        # and count the resulting population for each class in the children, but
        # instead we compute them in an iterative fashion, making this for loop
        # linear rather than quadratic.
        num_left = [0] * self.n_classes_
        num_right = num_parent.copy()
        for i in range(1, y.size):  # possible split positions
            c = classes[i - 1]
            num_left[c] += 1
            num_right[c] -= 1
            gini_left = 1.0 - sum(
                (num_left[x] / i) ** 2 for x in range(self.n_classes_)
            )
            gini_right = 1.0 - sum(
                (num_right[x] / (y.size - i)) ** 2 for x in range(self.n_classes_)
            )

            # The Gini impurity of a split is the weighted average of the Gini
            # impurity of the children.
            gini = (i * gini_left + (y.size - i) * gini_right) / y.size

            # The following condition is to make sure we don't try to split two
            # points with identical values for that feature, as it is impossible
            # (both have to end up on the same side of a split).
            if thresholds[i] == thresholds[i - 1]:
                continue

            if gini < best_gini:
                best_gini = gini
                best_idx = idx
                best_thr = (thresholds[i] + thresholds[i - 1]) / 2  # midpoint

    return best_idx, best_thr